[package]
name = "gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
bitmatch = "0.1.1"
enum-map = "2.1.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
